version: '3.8'

services:
  code_generator:
    build:
      context: .               
    image: fig2ui_code_generator
    env_file:
      - ./env
    ports:
      - "5000:5000"            
    restart: unless-stopped     